# These options apply to how the script will operate.
script_options:
  # Switch between testnet and mainnet
  # Setting this to False will use REAL funds, use at your own risk
  TESTNET: False
  LOG_TRADES: True
  LOG_FILE: 'trades.txt'


# These options apply to the trading methods the script executes
trading_options:
  # select what to pair the coins to and pull all coins paired with PAIR_WITH
  PAIR_WITH: USDT

  # Total amount per trade
  QUANTITY: 15

  # Use custom tickers.txt list for filtering pairs
  CUSTOM_LIST: False

  # List of pairs to exclude
  # by default we're excluding the most popular fiat pairs
  FIATS:
    - EURUSDT
    - GBPUSDT
    - JPYUSDT
    - USDUSDT
    - DOWN
    - UP

  # Maximum number of coins to hold
  MAX_COINS: 5

  # the amount of time in SECONDS to calculate the difference from the current price
  TIME_DIFFERENCE: 30

  # Number of times to check for TP/SL during each TIME_DIFFERENCE Minimum 1
  RECHECK_INTERVAL: 6

# Options that apply to specific strategies
strategy_options:
  volatility:
    # whether to use default settings or not; default is True
    USE_DEFAULT_STRATEGY: True

    # the difference in % between the first and second checks for the price.
    CHANGE_IN_PRICE: 0.8

    # define in % when to sell a coin that's not making a profit
    STOP_LOSS: 1.75

    # define in % when to take profit on a profitable coin
    TAKE_PROFIT: 2

  trailing_sl:
    # whether to use trailing stop loss or not; default is True
    USE_TRAILING_STOP_LOSS: True

    # when hit TAKE_PROFIT, move STOP_LOSS to TRAILING_STOP_LOSS percentage points below TAKE_PROFIT hence locking in profit
    # when hit TAKE_PROFIT, move TAKE_PROFIT up by TRAILING_TAKE_PROFIT percentage points
    TRAILING_STOP_LOSS: 0.5
    TRAILING_TAKE_PROFIT: 0.1

  stoch_rsi:
    # whether to use stoch_rsi or not; default is False
    USE_STOCH_RSI: False

    # time between candles
    #1min; 3min; 5min; 15min; 30min; 1hour; 2hour; 4hour; 6hour; 8hour; 12hour; 1day; 3day; 1week; 1month
    TIME_INTERVAL: 5min

    # instances tracked back from current time
    PERIOD: 14

    # RSI value for coins to be bought (default: 80)
    RSI_BUY_TRIGGER: 80

    # RSI value for coins to be sold (default: 20)
    RSI_SELL_TRIGGER: 20
