name: Release_Auto_Mail

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
          # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: ${{secrets.MAIL_ADDRESS}}
          to: fabian.wassermann04@gmail.com
          subject: Test
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
